### ISSUE TITLE
Campaign links

### ISSUE THREAD

**Issue by WerdnaStrebor** [danlproberts/marketo-to-csv#1]
The current API pulls back arrays based on lead id.  Can this be lead id and campaign id combination that is put into the array?

When the final file is compiled, the system can't work out what lead is associated with what campaign if a single lead has been used for multiple campaigns.  So if a lead is used on 3 different campaigns, the data returned only shows the information for one of the campaigns, but duplicated 3 times.  

I think this would be solved if each of the arrays that is created contained not only the lead id but the campaign id as well.  And then at the end, the knitting together of the different arrays would be done by linking on combination of lead id and campaign id.

**Comment by danlproberts** [comment]
Thank you for posting! I will look into this asap.

**Comment by danlproberts** [comment]
Try the up-to-date changes out now!
